# Generated by Django 5.0.3 on 2024-04-08 13:42

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def setup_groups_permissions(apps, schema_editor):
  """ Create lists:
    - list of groups
    - list of standard permission codes
    - list of permissions from permission codes
  Assign permissions to groups """
  add_issues, _ = Group.objects.get_or_create(name="Add issues and pics")
  view_issues, _ = Group.objects.get_or_create(name="View issues and pics, add comments")
  edit_issues, _ = Group.objects.get_or_create(name="Edit issues")
  delete_issues, _ = Group.objects.get_or_create(name="Delete issues, pics, comments")
  issue_groups = [add_issues, view_issues, edit_issues, delete_issues] # list of groups
  stdperms = {
    add_issues: ["add_issue", "add_issuepic"],
    view_issues: ["add_issue", "add_issuepic", "view_issue", "view_issuepic", "view_issuecomment", "add_issuecomment"],
    edit_issues: ["add_issue", "add_issuepic", "view_issue", "view_issuepic", "view_issuecomment", "add_issuecomment", "change_issue"],
    delete_issues: ["add_issue", "add_issuepic", "view_issue", "view_issuepic", "view_issuecomment", "add_issuecomment", "change_issue", "delete_issue", "delete_issuepic", "delete_issuecomment"],
  }
  for group, permcodes in stdperms.items():
    permissions = Permission.objects.filter(codename__in=permcodes)
    group.permissions.set(permissions)

class Migration(migrations.Migration):

  dependencies = [
    ('reg', '0001_initial'),
  ]

  operations = [
    migrations.RunPython(setup_groups_permissions),
  ]
