# Generated by Django 5.0.3 on 2024-05-03 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceevent',
            name='absence_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absence_type_event', to='homeoffice.absencetype', verbose_name='Absence type'),
        ),
        migrations.AlterField(
            model_name='absenceevent',
            name='employee_absence_group_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EAG_date', to='homeoffice.employeeabsencegroup', verbose_name='Employee absence group'),
        ),
        migrations.AlterField(
            model_name='absenceevent',
            name='employee_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_link', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
