# Generated by Django 5.0.3 on 2024-05-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0002_alter_absenceevent_absence_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absenceevent',
            options={'permissions': [('change_won', 'Can change only own events'), ('change_all', 'Can change all events')]},
        ),
    ]
