# Generated by Django 5.0.3 on 2024-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0003_alter_absenceevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absenceevent',
            options={'permissions': [('change_own', 'Can change only own events'), ('change_all', 'Can change all events')]},
        ),
    ]
