# Generated by Django 5.0.3 on 2024-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0006_alter_project_number_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimesetup',
            name='weekday',
            field=models.CharField(choices=[('1', 'Mo'), ('2', 'Di'), ('3', 'Mi'), ('4', 'Do'), ('5', 'Fr'), ('6', 'Sa'), ('7', 'So')], max_length=4, verbose_name='Weekday'),
        ),
    ]
