# Generated by Django 5.0.3 on 2024-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0007_alter_worktimesetup_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='working_time',
            field=models.BooleanField(default=False),
        ),
    ]
