# Generated by Django 5.0.3 on 2024-05-10 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0008_absencetype_working_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimesetup',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='DefaultWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Mo'), ('2', 'Di'), ('3', 'Mi'), ('4', 'Do'), ('5', 'Fr'), ('6', 'Sa'), ('7', 'So')], max_length=4, verbose_name='Weekday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
