# Generated by Django 5.0.3 on 2024-05-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0009_alter_worktimesetup_employee_defaultworktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultworktime',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='defaultworktime',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worktimesetup',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worktimesetup',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
