# Generated by Django 5.0.3 on 2024-05-17 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0012_alter_defaultworktime_working_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('sent', 'Gesendet'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='created', max_length=10, verbose_name='Event status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('working_time', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('break_time', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homeoffice.project', verbose_name='Project')),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeoffice.timesheet', verbose_name='Time Sheet')),
            ],
        ),
    ]
