# Generated by Django 5.0.3 on 2024-05-17 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0013_timesheet_timesheetline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetline',
            name='project',
        ),
        migrations.AddField(
            model_name='employee',
            name='default_time_category_is_office',
            field=models.BooleanField(blank=True, default=True, verbose_name='Default time category is office'),
        ),
        migrations.CreateModel(
            name='TimeSheetProjectLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeoffice.project', verbose_name='Project')),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeoffice.timesheet', verbose_name='Time Sheet')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holiday_setups', to='homeoffice.absencetype', verbose_name='Holiday setup')),
                ('illness_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='illness_setups', to='homeoffice.absencetype', verbose_name='Illness setup')),
                ('study_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_setups', to='homeoffice.absencetype', verbose_name='Study setup')),
            ],
        ),
    ]
