# Generated by Django 5.0.3 on 2024-05-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0014_remove_timesheetline_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetline',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='timesheetprojectline',
            name='employee',
        ),
    ]
