# Generated by Django 5.0.3 on 2024-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0015_remove_timesheetline_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetprojectline',
            name='working_time',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
