# Generated by Django 5.0.3 on 2024-06-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0016_timesheetprojectline_working_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeoffice.project', verbose_name='Project place')),
            ],
        ),
    ]
