# Generated by Django 5.0.3 on 2024-06-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0017_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
