# Generated by Django 5.0.3 on 2024-06-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0022_montagesetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Anfangsdatum')),
                ('end_date', models.DateField(verbose_name='Datum des Endes')),
                ('vehicle_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_service', to='homeoffice.vehicle', verbose_name='Vehicle')),
            ],
        ),
    ]
