# Generated by Django 5.0.3 on 2024-06-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeoffice', '0023_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers_task', to='homeoffice.employee', verbose_name='Worker'),
        ),
    ]
